#
# Makefile template for docker handling
#
all: usage

NAME=mywork
IMAGE=$(USER)/$(NAME)
#---------------------------------------------------------------------------------
docker d:
	@echo ""
	@echo "make (docker) [dp|ds|di]"
	@echo ""

ds:
	@docker search $(NAME)
dp:
	@docker pull $(IMAGE)
di:
	@docker inspect $(IMAGE)

#---------------------------------------------------------------------------------
md:
	vi README.md

make m:
	vi Makefile

usage:
	@echo "Docker Handling for '$(IMAGE)'"
	@echo "usage: make [docker|run]"
	@echo ""
